# This file was generated by https://github.com/MagnusOpera/forge/blob/main/.github/scripts/generate-homebrew-cask
cask "forge" do
  version "${FORGE_VERSION}"
  sha256 "${FORGE_MAC_ARM64_SHA256}"

  url "${FORGE_MAC_ARM64_URL}"
  name "Forge"
  desc "Focus-first desktop GitHub client"
  homepage "https://github.com/MagnusOpera/forge"

  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Forge.app"
end
